% flags
file_named = 0;
area_chosen = 0;
area_displayed = 0;
log_displayed = 0;
% Samp_Freq = 44100;
modzlabel = 'Magnitude';
del_az = 10; % set azimuth and elevation deltas
del_el = 10;

mod_all = figure('name','Modal Distribution - Main Window',...
          'NumberTitle','off','Menubar','none',...
          'units','normalized','Position',...
          [0.0019 0.4987 0.4258 0.4154],...
          'Resize','off'); % made unresizable to simplify matters - gino
axes('position',[0.14 0.2 0.85 0.78]);
axis('off');

mod_menu1 = uimenu('label','File','Accelerator','f');
mod_submenu1 = uimenu(mod_menu1,'label','Open','Accelerator','o',...
           'Callback','modfile2');
mod_submenu2 = uimenu(mod_menu1,'label','New','Accelerator','n',...
           'Callback','modnew');
mod_submenu3 = uimenu(mod_menu1,'label','Close','Accelerator','c',...      
           'Callback','modclose');

mod_button = uicontrol('style','pushbutton','string',...
             'Choose Area','units','normalized',...
             'position',[0 0 0.3 0.06],...
             'Callback','modchos2');
mod_display = uicontrol('style','pushbutton','string',...
        'Display','units','normalized',...
        'position',[0.305 0 0.2 0.06],...
        'CallBack','mod_baby');
lin_display = uicontrol(mod_all,'style','pushbutton',...
                'string','[Lin]','callback','modlin',...
                'units','normalized',...
                'position',[0.51 0 0.1 0.06],...
                'enable','off');
log_display = uicontrol(mod_all,'style','pushbutton',...
                'string','Log','callback','modlog',...
                'units','normalized',...
                'position',[0.615 0 0.1 0.06],...
                'enable','off');
log_string = uicontrol(mod_all,'style','text',...
                'string','dB range',...
                'units','normalized',...
                'position',[0.80 0 0.10 0.06]);
log_range = uicontrol(mod_all,'style','edit',...      
                'BackGroundColor','white',...
                'units','normalized',...
                'position',[0.895 0.004 0.1 0.055]);

freq_str =  uicontrol(mod_all,'Style','text','position',...
                [1 20 30 14],'string','Freq');
freq_from =  uicontrol(mod_all,'Style','edit','position',...
                [31 20 40 14],'string','0','BackGroundColor','white');
freq_str2 = uicontrol(mod_all,'Style','text','position',...
                [71 20 20 14],'string','to');
freq_to =  uicontrol(mod_all,'Style','edit','position',...
                [91 20 40 14],'string','0','BackGroundColor','white');
freq_str3 = uicontrol(mod_all,'Style','text','position',...
                [131 20 20 14],'string','Hz');
time_str =  uicontrol(mod_all,'Style','text','position',...
                [161 20 40 14],'string','Time');
time_from =  uicontrol(mod_all,'Style','edit','position',...
                [201 20 40 14],'string','0','BackGroundColor','white');
time_str2 = uicontrol(mod_all,'Style','text','position',...
                [241 20 20 14],'string','to');
time_to =  uicontrol(mod_all,'Style','edit','position',...
                [261 20 40 14],'string','0','BackGroundColor','white');
time_str3 = uicontrol(mod_all,'Style','text','position',...       
                [301 20 30 14],'string','msec');


%'string',sprintf('%1.0f',db_range),...
mod_some = figure('name','Modal Distribution - Sub Window',...
           'NumberTitle','off','Menubar','none',...
           'units','normalized','Position',...
           [0.436 0.413 0.559 0.5]);
axes('position',[0.15 0.2 0.78 0.78],'SortMethod','childorder','ydir','reverse');
axis('off');
mod_opt = uimenu(mod_some,'label','Options');
mod_subopt1 = uimenu(mod_opt,'label','Print',...
                'callback','modprint');
mod_subopt2 = uimenu(mod_opt,'label','3-D Plot',...
                'callback','mod_baby');
mod_subopt3 = uimenu(mod_opt,'label','Image Plot',...
                'callback','mod_imag');
mod_subopt4 = uimenu(mod_opt,'label','PColor Plot',...
                'callback','mod_pcol');
but_azimuth = uicontrol(mod_some,'Style','pushbutton',...
                  'units','normalized',...
                  'position',[0 0 0.1 0.06],'string',...   
                  'Azimuth',...
                  'HorizontalAlignment','center',...
                  'callback','az_reset',...
                  'enable','off');
but_inc1 = uicontrol(mod_some,'style','pushbutton',...
                'string','+','units','normalized',...
                'position',[0.105 0 0.05 0.06],...
                'callback','az_inc',...
                'enable','off');
but_dec1 = uicontrol(mod_some,'style','pushbutton',...
                'string','-','units','normalized',...
                'position',[0.155 0 0.05 0.06],...
                'callback','az_dec',...
                'enable','off');
but_elevation = uicontrol(mod_some,'style','pushbutton',...
                  'units','normalized',...
                  'position',[0.235 0 0.1 0.06],'string',...
                  'Elevation',...
                  'HorizontalAlignment','center',...
                  'callback','el_reset',...
                'enable','off');
but_inc2 = uicontrol(mod_some,'style','pushbutton',...
                'string','+','units','normalized',...
                'position',[0.34 0 0.05 0.06],...
                'callback','el_inc',...
                'enable','off');
but_dec2 = uicontrol(mod_some,'style','pushbutton',...
                'string','-','units','normalized',...
                'position',[0.39 0 0.05 0.06],...        
                'callback','el_dec',...
                'enable','off');
but_coarse = uicontrol(mod_some,'style','pushbutton',...
                'string','[Coarse]','units',...
                'normalized','position',[0.465 0 0.1 0.06],...
                'callback','modcoars',...
                'enable','off');
but_fine = uicontrol(mod_some,'style','pushbutton',...
                'string','Fine','units',...
                'normalized','position',[0.565 0 0.1 0.06],...
                'callback','modfine',...
                'enable','off');
but_default = uicontrol(mod_some,'style','pushbutton',...
                'string','Reset View','units',...
                'normalized','position',[0.675 0 0.15 0.06],...
                'callback','mod_azel',...
                'enable','off');