function sig = sossynth(filename, workspace)
% SYNTH(FILENAME, MODE)
%   synthesize signal from its MD  saved in FILENAME.BIN
%   and the obtained parameters saved in WORKSPACE.MAT generated by
%   PARTIAL.M
%
%
% Created by Jhaezminne Gayo for ECE 198 February 2020

%addpath('MFiles');


load(workspace);
sig = 0; 
for j  = 1:numel(sbin) %per partial
    [amp,freq,Fs,dt] = modalest(filename,sbin(j),ebin(j));
                % amp contains amplitude estimate
                % freq contains frequency estimate
                % Fs is the sampling frequency
                % dt is the time interval   
  
    dt = dt/1000; 
   % par = sosinterp(amp, freq, Fs, dt); 
   % sig = sig + par; 
    
end

audiowrite('A1_synth.wav', sig, Fs);
